public class CommonsCommunityManagementControlResult {
        
    public String groupName { get; set; }
    public String question { get; set; }
    public String student { get; set; }
    public String studentResponse { get; set; }
    public String communityAccessControlId { get; set; }
    public String mentorResponse { get; set; }
    public FeedItemWithUserType feedItem { get; set; }
    
}